robot1:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz  
      
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      cartesian_motion_controller:
        type: cartesian_motion_controller/CartesianMotionController

      motion_control_handle:
        type: cartesian_controller_handles/MotionControlHandle

robot2:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz  
      
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      cartesian_motion_controller:
        type: cartesian_motion_controller/CartesianMotionController

      motion_control_handle:
        type: cartesian_controller_handles/MotionControlHandle


robot1:
  cartesian_motion_controller:
    ros__parameters:

      # See the cartesian_compliance_controller
      end_effector_link: "1_camera"
      robot_base_link: "1_base_link"
      joints:
        - 1_shoulder_pan_joint
        - 1_shoulder_lift_joint
        - 1_elbow_joint
        - 1_wrist_1_joint
        - 1_wrist_2_joint
        - 1_wrist_3_joint

      # See the cartesian_compliance_controller
      command_interfaces:
        - position
          #- velocity
      solver:
        error_scale: 1.0
        iterations: 1

      pd_gains:
          trans_x: {p: 20.0}
          trans_y: {p: 20.0}
          trans_z: {p: 20.0}
          rot_x: {p: 3.0}
          rot_y: {p: 3.0}
          rot_z: {p: 3.0}
robot1:
  motion_control_handle:
    ros__parameters:
      end_effector_link: "1_camera"
      robot_base_link: "1_base_link"
      ft_sensor_ref_link: "1_wrist_3_link"
      joints:
        - 1_shoulder_pan_joint
        - 1_shoulder_lift_joint
        - 1_elbow_joint
        - 1_wrist_1_joint
        - 1_wrist_2_joint
        - 1_wrist_3_joint



robot2:
  cartesian_motion_controller:
    ros__parameters:

      # See the cartesian_compliance_controller
      end_effector_link: "2_camera"
      robot_base_link: "2_base_link"
      joints:
        - 2_shoulder_pan_joint
        - 2_shoulder_lift_joint
        - 2_elbow_joint
        - 2_wrist_1_joint
        - 2_wrist_2_joint
        - 2_wrist_3_joint

      # See the cartesian_compliance_controller
      command_interfaces:
        - position
          #- velocity
      solver:
        error_scale: 1.0
        iterations: 1

      pd_gains:
          trans_x: {p: 20.0}
          trans_y: {p: 20.0}
          trans_z: {p: 20.0}
          rot_x: {p: 3.0}
          rot_y: {p: 3.0}
          rot_z: {p: 3.0}

robot2:
  motion_control_handle:
    ros__parameters:
      end_effector_link: "2_camera"
      robot_base_link: "2_base_link"
      ft_sensor_ref_link: "2_wrist_3_link"
      joints:
        - 2_shoulder_pan_joint
        - 2_shoulder_lift_joint
        - 2_elbow_joint
        - 2_wrist_1_joint
        - 2_wrist_2_joint
        - 2_wrist_3_joint